# Generated by Django 3.2.6 on 2021-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210810_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supporting',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, null=True),
        ),
    ]
