# Generated by Django 3.2.6 on 2021-08-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_supporting'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client', to_field='email'),
        ),
    ]
