# Generated by Django 3.2.6 on 2021-08-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Confirmed', 'Confirmed'), ('Requirement Gathering', 'Requirement Gathering'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Client side hold', 'Client side hold'), ('Complete', 'Complete')], default='Lead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', to_field='email'),
        ),
    ]
