# Generated by Django 3.2.6 on 2021-08-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_cost',
        ),
    ]
