# Generated by Django 3.2.6 on 2021-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210810_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Application', 'Application'), ('Digital Marketing', 'Digital Marketing')], default='Website', max_length=50, null=True),
        ),
    ]
