# Generated by Django 3.2.6 on 2021-08-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
    ]
