# Generated by Django 3.2.6 on 2021-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_name_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hosting_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Confirmed', 'Confirmed'), ('Requirement Gathering', 'Requirement Gathering'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Client side hold', 'Client side hold'), ('Complete', 'Complete'), ('Deployed', 'Deployed')], default='Lead', max_length=50, null=True),
        ),
    ]
