# Generated by Django 3.2.6 on 2021-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210810_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hosting_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
