# Generated by Django 3.2.6 on 2021-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210810_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
