# Generated by Django 3.2.6 on 2021-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_supporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
